### ISSUE TITLE
Dependencies are not available anymore

### ISSUE THREAD

**Issue by ghost** [lgrahl/query-lsf-marks#1]
Is there any way to get the dependencies for this little script?

When trying to install  zwnflibs (logging & notify), and zwnfqan:

`
Command "hg clone --noupdate -q https://vcs.zwuenf.org/hg/lgrahl/zwnflibs/logging /tmp/pip-vy0b388y-build" failed with error code 255 in None`

Thank you.

**Comment by lgrahl** [comment]
These dependencies are ancient and I don't think they're a good idea any more. I've started cleaning up the script and will let you know when it's ready. Maybe this evening.

**Comment by lgrahl** [comment]
Fixed in 5c653612f2e8317fb61af4822930df2932d673f2. Can you check it out? I've only tried it on Ubuntu so far.

**Comment by ghost** [comment]
Thank you for cleaning out all the old dependencies!

Did get it to work on my RaspberryPi with Debian Jessie for the qis Server at Uni Stuttgart. 

Thank you!

**Comment by lgrahl** [comment]
Cool! I wasn't sure this would work for other universities that use this system, so that's good to know. What did you have to modify to make it work with the qis server of Stuttgart University? Maybe we can make this tool more universal if it's just swapping the URLs.

**Comment by ghost** [comment]
I thought about publishing it, but normally as I just wanted to get it to work last night I hard coded everything in. Also I run this headless so I get notifications via pushbullet.py, which is probably already really unusual. I would propose some sort of email notification.
Basically every user needs to get his "own" link form the qis webinterface for his own degree. I think this can be automated, some Android apps can already do that.
I changed the parser to lxml, the html parser did cut of after the first bold table row - no idea why. 

So I had a deeper look into the LSF:
First this url would need to be accessed:
`https://lsf.uni-stuttgart.de/qisserver/rds?state=notenspiegelStudent&next=tree.vm&nextdir=qispos/notenspiegel/student&navigationPosition=functions%2CnotenspiegelStudent&breadcrumb=notenspiegel&topitem=functions&subitem=notenspiegelStudent&asi={}`

On this page BS could search after `class=treelist` and parse the url of the "info" picture.

**Comment by lgrahl** [comment]
> Also I run this headless so I get notifications via pushbullet.py, which is probably already really unusual.

I don't think it's unusual. Notification style could be made configurable. A notification style to output to stdout would be fine, too, so people can pipe it to wherever they want.

> I would propose some sort of email notification.

Could be yet another notification style. Email requires quite a lot of configuration, though. Making this work through the CLI would at least require using a proper CLI tool such as [click](http://click.pocoo.org/6/).

> On this page BS could search after `class=treelist` and parse the url of the "info" picture.

I see. Well, I'm open for pull requests. :)
